### ISSUE TITLE
Problema na listagem de clientes

### ISSUE THREAD

**Issue by FastFire377** [Quywed/OficinaDoZe_v2#11]
Dá erro na função de listagem de clientes com index out of range

**Comment by FastFire377** [comment]
Penso que esteja resolvido, falta testar.

**Comment by Quywed** [comment]
Não, não deu. O teus pushes não estão a funcionar

**Comment by Quywed** [comment]
Vou resolver

**Comment by Quywed** [comment]
Esqueci-me de dizer que resolvi a listagem de clientes
